version: '3.7'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    env_file: .env
    volumes:
      - ./minio_data:/data
      - ./nginx/ssl:/root/.minio/certs  # SSL 인증서 마운트
    ports:
      - "9000:9000"  # MinIO 웹 인터페이스 포트
      - "9001:9001"  # MinIO 관리 콘솔 포트 (선택사항)
    command: server /data --console-address ":9001"
    restart: always  # 컨테이너가 중지되면 항상 재시작
    networks:
      - proxynet
  
  # nginx:
  #   build:
  #     context: ./nginx
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/log:/var/log/nginx/
  #     - ./nginx/ssl:/usr/share/nginx/ssl/
  #   networks:
  #     - proxynet

networks:
  proxynet:
    external: true